name: homl3
channels:
  - conda-forge
  - defaults
dependencies:
  - box2d-py # used only in chapter 18, exercise 8
  - ffmpeg # used only in the matplotlib tutorial to generate animations
  - graphviz # used only in chapter 6 for dot files
  - python-graphviz # used only in chapter 6 for dot files
  - ipython # a powerful Python shell
  - ipywidgets # optionally used only in chapter 12 for tqdm in Jupyter
  - joblib= # used only in chapter 2 to save/load Scikit-Learn models
  - jupyterlab # to edit and run Jupyter notebooks
  - matplotlib # beautiful plots. See tutorial tools_matplotlib.ipynb
  - nbdime # optional tool to diff Jupyter notebooks
  - nltk # optionally used in chapter 3, exercise 4
  - numexpr # used only in the Pandas tutorial for numerical expressions
  - numpy # Powerful n-dimensional arrays and numerical computing tools
  - pandas # data analysis and manipulation tool
  - polars
  - pillow # image manipulation library, (used by matplotlib.image.imread)
  - pip # Python's package-management system
  - py-xgboost # used only in chapter 6 for optimized Gradient Boosting
  - pydot # used only for in chapter 10 for tf.keras.utils.plot_model()
  - python # your beloved programming language! :)
  - requests # used only in chapter 19 for REST API queries
  - scikit-learn # machine learning library
  - scipy # scientific/technical computing library
  - statsmodels # used only in chapter 15 for time series analysis
  - tqdm # used only in chapter 12 to display nice progress bars
  - wheel # built-package format for pip
  - widgetsnbextensionE # interactive HTML widgets for Jupyter notebooks
  - pip:
      - keras-tuner # used in chapters 10 and 19 for hyperparameter tuning
      - tensorboard-plugin-profile # profiling plugin for TensorBoard
      - tensorboard # TensorFlow's visualization toolkit
      - tensorflow-addons # used in chapters 11 & 16 (for AdamW & seq2seq)
      - tensorflow-datasets # datasets repository, ready to use
      - tensorflow-hub # trained ML models repository, ready to use
      - tensorflow-serving-api # or tensorflow-serving-api-gpu if gpu
      - tensorflow # Deep Learning library
      - transformers # Natural Language Processing lib for TF or PyTorch
      - urlextract # optionally used in chapter 3, exercise 4
      - gym[classic_control,atari,accept-rom-license] # used only in ch18
      - google-cloud-aiplatform # used only in chapter 19
      - google-cloud-storage # used only in chapter 19
